ersion: "2"

services:

  elasticsearch:
    image: elasticsearch:2.4
    ports:
    - "9200:9200"
    volumes:
    - ./esdata/:/usr/share/elasticsearch/data/

  kibana:
    image: kibana:4.6
    ports:
    - "5601:5601"
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200